config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'

  resources :tasks do
    resources :sub_tasks
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sub_task.rb
class SubTask < ApplicationRecord
  belongs_to :task
  validates :text, :summary, presence: true
  validates :important, inclusion: { in: %w(urgent high low normal) }, allow_nil: true, allow_blank: true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :sub_tasks, dependent: :destroy
  validates :text, :summary, presence: true
  validates :important, inclusion: { in: %w(urgent high low normal) },allow_nil: true, allow_blank: true

  def self.search(term)
    if term
      where('summary LIKE ? OR text LIKE ? OR important LIKE ?', "%#{term}%", "%#{term}%", "%#{term}%")
    else
      all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController

      before_action :get_task

      def create
        @sub_task = @task.sub_tasks.create!(sub_task_params)
        redirect_to task_path(@task)

      end

      def edit
        @sub_task = @task.sub_tasks.find(params[:id])
      end

      def update
        @sub_task = @task.sub_tasks.find(params[:id])

        if @sub_task.update(sub_task_params)
          redirect_to task_path(@task)
        else
          render 'Edit'
        end
      end

      def destroy
        @sub_task = @task.sub_tasks.find(params[:id])
        @sub_task.destroy
        redirect_to task_path(@task)
      end

      private
      def get_task
        @task = Task.find(params[:task_id])
      end

      def sub_task_params
        params.require(:sub_task).permit(:summary, :text, :due_date, :important)
      end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def index
      @tasks = Task.search(params[:term])
    end

    def show
      @task = Task.find(params[:id])
    end

    def new
      @task = Task.new
    end

    def create
      @task = Task.new(task_params)

      if @task.save
        redirect_to @task
      else
        render 'new'
      end
    end

    def edit
      @task = Task.find(params[:id])
    end

    def update
      @task = Task.find(params[:id])

      if @task.update(task_params)
        redirect_to @task
      else
        render 'edit'
      end
    end

    def destroy
      @task = Task.find(params[:id])
      @task.destroy

      redirect_to tasks_path
    end

    private 
    def task_params
        params.require(:task).permit(:summary, :text, :due_date, :important, :term)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sub_tasks_helper.rb
module SubTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodolistPostgres</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sub_tasks/_form.html.erb
<%= form_with model: [ @task, @task.sub_tasks.build] do |form| %>

  <p>
    <%= form.label :summary %><br>
    <%= form.text_field :summary %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.label :due_date %>
    <%= form.datetime_field :due_date %>
  </p>

  <p>
    <%= form.label :important %>
    <%= form.text_field :important %>
    <mark>Can be set as: urgent, high, low, normal</mark>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/sub_tasks/_sub_task.html.erb
<fieldset>
<p>
  <strong>Summary:</strong>
  <%= sub_task.summary %>
</p>

<p>
  <strong>Text:</strong>
  <%= sub_task.text %>
</p>

<p>
  <strong>Due date sub_tasks:</strong>
  <%= sub_task.due_date %>
<p/>

<p>
  <strong>Important:</strong>
  <%= sub_task.important %>
</p>


<table>
  <tr>
    <td><%= link_to 'Edit sub_task', edit_task_sub_task_path(task_id: @task.id, id: sub_task.id) %></td>
    <td><%= link_to 'Destroy', [sub_task.task, sub_task],
                              method: :delete,
                              data: { confirm: 'Are you sure?'} %></td>
  </tr>
</table>
</fieldset>

app/views/sub_tasks/edit.html.erb
<head>
  <style>
    body{
      background-color: lightgray;
    }
  </style>
</head>

<body>
<h1>Edit sub_task</h1>

<%= form_with model: [@task,@sub_task] do |form| %>
<p>
  <%= form.label :summary %><br>
  <%= form.text_field :summary %>
</p>

<p>
  <%= form.label :text %><br>
  <%= form.text_area :text %>
</p>

<p>
  <%= form.label :due_date %>
  <%= form.datetime_field :due_date %>
</p>

<p>
  <%= form.label :important %>
  <%= form.text_field :important %>
  <mark>Can be set as: urgent, high, low, normal</mark>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>
<%= link_to 'Back',task_path(@task) %>
</body>

app/views/tasks/_form.html.erb
<%= form_with model: @task, local: true do |form| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %>. This task can not be saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :summary %><br>
    <%= form.text_field :summary %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.label :due_date %>
    <%= form.datetime_field :due_date %>
  </p>

  <p>
    <%= form.label :important %>
    <%= form.text_field :important %>
    <mark>Can be set as: urgent, high, low, normal</mark>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/edit.html.erb
<head>
  <style>
    body{
      background-color: lightgray;
    }
  </style>
</head>

<body>
  <h1>Edit task</h1>
  <%= render 'form' %>
  <%= link_to 'Back', tasks_path %>
</body>

app/views/tasks/index.html.erb
<head>
<style>
h1 {
  display: block;
  color: red;
  text-align: center;
}

table,td,th {
  border: 1px solid black;
  border-collapse: collapse;
}
body{
  background-color: lightgray;
}
</style>
</head>

<body>
<h1>Listing tasks</h1>
<!--Seach form -->
<div>
<%= form_tag(tasks_path, method: :get) do %>
  <%= text_field_tag :term %>
  <%= submit_tag 'Search' %><mark> Search by text only</mark>
<% end %>
</div>
<!--Table listing task -->
<table>
  <tr>
    <th>Summary</th>
    <th>Text</th>
    <th>Due date</th>
    <th>Imporant</th>
  </tr>

  <% @tasks.order(due_date: :desc).each do |task| %>
    <tr>
      <td><%= task.summary %></td>
      <td><%= task.text %></td>
      <td><%= task.due_date %></td>
      <td><%= task.important %></td>
      <td><p><%= link_to 'Show', task_path(task) %></p>
          <p><%= link_to 'Edit', edit_task_path(task) %></p>
          <p><%= link_to 'Destroy', task_path(task),
                              method: :delete, data: { confirm: 'Are you sure?'} %></p></td>
    </tr>
  <% end %>
</table>

<p>
<%= link_to 'New task', new_task_path %>
</p>
</body>

app/views/tasks/new.html.erb
<head>
  <style>
    body{
      background-color: lightgray;
    }
  </style>
</head>

<body>
  <h1>New task</h1>

  <%= render 'form' %>

  <%= link_to 'Back', tasks_path %>
</body>

app/views/tasks/show.html.erb
<head>
<!--using internal css before complete external file-->
  <style>
  div {
    display: block;
    text-align: center;
    padding: 10px;
    font-size: 1.2em;
  }
  h1 {
    display: block;
    color: red;
    text-align: center;
  }
  h3 {
    text-align: center;
    color: blue;
  }
  body{
    background-color: lightgray;
  }
  </style>


</head>

<body>
  <h1>Task</h1>
  <hr>
  <div>
    <p>
      <strong>Summary:</strong>
      <%= @task.summary %>
    </p>

    <p>
      <strong>Text:</strong>
      <%= @task.text %>
    </p>

    <p>
      <strong>Due date:</strong>
      <%= @task.due_date %>
    </p>

    <p>
      <strong>Important:</strong>
      <%= @task.important %>
    </p>
  </div>

  <hr>
  <h3>Sub tasks</h3>
  <%= render @task.sub_tasks.order(due_date: :desc) %>
  <fieldset>
    <legend><strong>Add sub_task</strong></legend>
    <%= render 'sub_tasks/form' %>
  </fieldset>

  <%= link_to 'Edit', edit_task_path(@task) %>
  <%= link_to 'Back', tasks_path %>
</body>

app/views/welcome/index.html.erb
<head>
  <style>
    body{
      text-align: center;
      font-size: 2em;
      background-color: black;
      color: white;
    }
  </style>
</head>

<body>
<h1>Welcome to task manager</h1>
<%= link_to 'My tasks', tasks_path %>
</body>